#!/usr/bin/env bash

BRIGHTNESS_STEPS=5

function get_brightness {

  brightnessctl i | grep -oP '\(\K[^%\)]+'

}

function send_notification {

  brightness=$(get_brightness)

  dunstify "Brightness : $brightness%" -r 5555 -u normal

}

case $1 in
  up)
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%+" -q
    send_notification
    ;;
  down)
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%-" -q
    send_notification
    ;;
esac
