#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

# Configs

bspc config border_width         	1
bspc config window_gap           	10
bspc config split_ratio          	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true
bspc config initial_polarity 		first_child
bspc config focused_border_color	"#555555"

# Rules

bspc rule -a Google-chrome desktop='^3'
bspc rule -a discord dessktop='^4'
bspc rule -a Com.github.xournalpp.xournalpp desktop='^1'
bspc rule -a ranger state=floating
bspc rule -a mpv state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a org.gnome.Nautilus state=floating

# Autostart

redshift -P -O 3500k
xsetroot -cursor_name left_ptr
