#!/usr/bin/env bash

BRIGHTNESS_STEPS=5

function get_brightness {

  brightnessctl i | grep -oP '\(\K[^%\)]+'

}

function send_notification {

  brightness=$(get_brightness)

  dunstify -u low -t 5555 -h string:x-dunst-stack-tag:brightness "Brightness : $brightness%"

}

case $1 in
  up)
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%+" -q
    send_notification
    ;;
  down)
    brightnessctl set "${BRIGHTNESS_STEPS:-5}%-" -q
    send_notification
    ;;
esac
