#!/bin/bash

# Define o limite de volume máximo para 100%
wpctl set-metadata @DEFAULT_AUDIO_SINK@ api.alsa.volume-limit 1.0

# Função para obter o volume atual
get_volume() {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100}' | cut -d'.' -f1
}

# Função para exibir notificações
send_notification() {
    local message=$1
    dunstify -u low -t 5555 -h string:x-dunst-stack-tag:brightness "$message"
}

# Verifica o parâmetro e ajusta o volume
case $1 in
    up)
        volume=$(get_volume)
        if [ "$volume" -lt 100 ]; then
            wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
        fi
        volume=$(get_volume)
        send_notification "Volume : $volume%"
        ;;
    down)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
        volume=$(get_volume)
        send_notification "Volume : $volume%"
        ;;
    mute)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
        if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q "MUTED"; then
            send_notification "Volume : 0%"
        else
            volume=$(get_volume)
            send_notification "Volume : $volume%"
        fi
        ;;
    *)
        echo "Uso: $0 {up|down|mute}"
        exit 1
        ;;
esac
